console.log("Apna College");
console.log("Purnima Sharma");
fullname = "Nidhi Sharma";
console.log(fullname);
let name = "Alok Sharma";
name ="Raman sharma";
console.log(name);
const Name = "Aman sharma";
// Name = "kunal";
// console.log(Name);
let car = "bmw";
console.log(car);